title: standaard-projectsjabloon
hero_image: images/banner.png
description: default-project-template description
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  0:
title: What you will make
  1:
title: Step title
  2:
title: What can you do now?
  3:
title: Quick quiz
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
  completion:
    - external
