title: default-project-template
hero_image: images/banner.png
description: default-project-template description
version: 1
listed: false
copyedit: false
test_string: jo
last_tested: "2025-01-01"
steps:
  - title: What you will make
  - title: Step title
  - title: What can you do now?
  - title: Quick quiz
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
  completion:
    - external
