"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    # copied from old crowdin.yml config
    "source": "/en/**/*.*",
    "translation": "/%locale%/**/%original_file_name%",
  }
]